# Dataset division

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_parquet("datasets/questoes_tratadas.parquet")

train_df, rem_df = train_test_split(df, test_size=0.3, random_state=42)
val_df, test_df = train_test_split(rem_df, test_size=0.5, random_state=42)

print(f"Train set size: {len(train_df)}")
print(f"Validation set size: {len(val_df)}")
print(f"Test set size: {len(test_df)}")

train_df.to_parquet("datasets/divided/train.parquet", index=False)
val_df.to_parquet("datasets/divided/val.parquet", index=False)
test_df.to_parquet("datasets/divided/test.parquet", index=False)

# Grid search for classic hyperparams

In [1]:
import os
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline

from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

# ========= cria pastas =========
RESULTS_FOLDER = "results/grid-search"
os.makedirs(RESULTS_FOLDER, exist_ok=True)

CACHE_FOLDER = "cache_dir"
os.makedirs(CACHE_FOLDER, exist_ok=True)

# ========= dados =========
df_train = pd.read_parquet("datasets/divided/train.parquet")
df_val = pd.read_parquet("datasets/divided/val.parquet")

df_train = pd.concat([df_train, df_val], ignore_index=True)

# ========= split =========
X_train = df_train["texto_lem"]
y_train = df_train["materia"]

cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

# ========= steps fixos =========
vectorizer = TfidfVectorizer(
    max_features=None,
    ngram_range=(1, 2),
    min_df=3,
    max_df=0.8,
)
selector = SelectKBest(chi2, k=20000)

test_models = {
    "LinearSVC": {
        "model": LinearSVC(random_state=42, max_iter=1000),
        "params": {
            "clf__C": np.logspace(-2, 1, 7),
            "clf__class_weight": ["balanced", None],
        },
    },
    "LogisticRegression": {
        "model": LogisticRegression(random_state=42, max_iter=1000),
        "params": {
            "clf__C": np.logspace(-2, 1, 7),
            "clf__class_weight": ["balanced", None],
            "clf__solver": ["lbfgs", "saga"],
        },
    },
    "RandomForest": {
        "model": RandomForestClassifier(random_state=42),
        "params": {
            "clf__n_estimators": [200, 500, 800],
            "clf__max_depth": [10, 20, 30],
            "clf__class_weight": ["balanced_subsample", "balanced", None],
        },
    },
    "NaiveBayes": {
        "model": MultinomialNB(),
        "params": {
            "clf__alpha": np.logspace(-2, 1, 9),
        },
    },
}

# ========= pipeline com cache =========
pipeline = Pipeline(
    [
        ("tfidf", vectorizer),
        ("chi2", selector),
        ("clf", LinearSVC()),
    ],
    memory=CACHE_FOLDER,
)


summary_rows = []

for nome, spec in test_models.items():
    print(f"\n=== Rodando GridSearchCV para {nome} ===")
    pipeline.set_params(clf=spec["model"])
    params = spec["params"]

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=params,
        scoring="f1_macro",
        cv=cv,
        n_jobs=-1,
        verbose=2,
        refit=True,
        return_train_score=False,
        error_score="raise",
    )

    grid.fit(X_train, y_train)  # type: ignore

    # ---- salva resultados do Grid ----
    results = pd.DataFrame(grid.cv_results_)
    cols = ["rank_test_score", "mean_test_score"] + [
        c for c in results.columns if c.startswith("param_")
    ]
    results = results[cols].copy()
    results["mean_test_score"] = results["mean_test_score"].round(4)
    results = results.sort_values(by="rank_test_score")
    results_path = f"{RESULTS_FOLDER}/gridsearch_results_{nome.lower()}.csv"
    results.to_csv(results_path, index=False)

=== Rodando GridSearchCV para LinearSVC ===
Fitting 4 folds for each of 14 candidates, totalling 56 fits
[CV] END ............clf__C=0.01, clf__class_weight=balanced; total time=   5.1s
[CV] END ............clf__C=0.01, clf__class_weight=balanced; total time=   5.0s
[CV] END ................clf__C=0.01, clf__class_weight=None; total time=   4.9s
[CV] END ............clf__C=0.01, clf__class_weight=balanced; total time=   5.0s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced; total time=   4.8s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced; total time=   4.9s
[CV] END .clf__C=0.03162277660168379, clf__class_weight=None; total time=   4.9s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced; total time=   5.0s
[CV] END ................clf__C=0.01, clf__class_weight=None; total time=   5.3s
[CV] END ............clf__C=0.01, clf__class_weight=balanced; total time=   5.8s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced; total time=   5.3s
[CV] END ................clf__C=0.01, clf__class_weight=None; total time=   5.7s
[CV] END ................clf__C=0.01, clf__class_weight=None; total time=   5.6s
[CV] END .clf__C=0.03162277660168379, clf__class_weight=None; total time=   5.4s
[CV] END .clf__C=0.03162277660168379, clf__class_weight=None; total time=   5.2s
[CV] END .clf__C=0.03162277660168379, clf__class_weight=None; total time=   5.6s
[CV] END .............clf__C=0.1, clf__class_weight=balanced; total time=   1.8s
[CV] END .............clf__C=0.1, clf__class_weight=balanced; total time=   1.9s
[CV] END .............clf__C=0.1, clf__class_weight=balanced; total time=   1.9s
[CV] END .............clf__C=0.1, clf__class_weight=balanced; total time=   2.0s
[CV] END .................clf__C=0.1, clf__class_weight=None; total time=   1.9s
[CV] END .................clf__C=0.1, clf__class_weight=None; total time=   2.0s
[CV] END .................clf__C=0.1, clf__class_weight=None; total time=   1.9s
[CV] END .................clf__C=0.1, clf__class_weight=None; total time=   2.1s
[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced; total time=   2.1s
[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced; total time=   2.5s
[CV] END .clf__C=0.31622776601683794, clf__class_weight=None; total time=   2.3s
[CV] END .clf__C=0.31622776601683794, clf__class_weight=None; total time=   2.3s
[CV] END .clf__C=0.31622776601683794, clf__class_weight=None; total time=   2.2s
[CV] END .clf__C=0.31622776601683794, clf__class_weight=None; total time=   3.1s
[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced; total time=   3.5s
[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced; total time=   3.5s
[CV] END .............clf__C=1.0, clf__class_weight=balanced; total time=   2.8s
[CV] END .................clf__C=1.0, clf__class_weight=None; total time=   2.6s
[CV] END .............clf__C=1.0, clf__class_weight=balanced; total time=   2.7s
[CV] END .................clf__C=1.0, clf__class_weight=None; total time=   2.6s
[CV] END .............clf__C=1.0, clf__class_weight=balanced; total time=   2.9s
[CV] END .................clf__C=1.0, clf__class_weight=None; total time=   2.6s
[CV] END .................clf__C=1.0, clf__class_weight=None; total time=   2.8s
[CV] END .............clf__C=1.0, clf__class_weight=balanced; total time=   3.8s
[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced; total time=   3.7s
[CV] END ..clf__C=3.1622776601683795, clf__class_weight=None; total time=   3.2s
[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced; total time=   4.3s
[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced; total time=   4.4s
[CV] END ..clf__C=3.1622776601683795, clf__class_weight=None; total time=   3.7s
[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced; total time=   4.5s
[CV] END ..clf__C=3.1622776601683795, clf__class_weight=None; total time=   3.9s
[CV] END ..clf__C=3.1622776601683795, clf__class_weight=None; total time=   3.8s

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END ................clf__C=10.0, clf__class_weight=None; total time=   4.7s
[CV] END ............clf__C=10.0, clf__class_weight=balanced; total time=   4.9s
[CV] END ................clf__C=10.0, clf__class_weight=None; total time=   4.8s
[CV] END ................clf__C=10.0, clf__class_weight=None; total time=   4.4s
[CV] END ............clf__C=10.0, clf__class_weight=balanced; total time=   5.2s
[CV] END ............clf__C=10.0, clf__class_weight=balanced; total time=   5.0s
[CV] END ................clf__C=10.0, clf__class_weight=None; total time=   4.6s
[CV] END ............clf__C=10.0, clf__class_weight=balanced; total time=   5.2s

=== Rodando GridSearchCV para LogisticRegression ===
Fitting 4 folds for each of 28 candidates, totalling 112 fits
[CV] END clf__C=0.01, clf__class_weight=balanced, clf__solver=lbfgs; total time=   2.1s
[CV] END clf__C=0.01, clf__class_weight=balanced, clf__solver=lbfgs; total time=   2.1s
[CV] END clf__C=0.01, clf__class_weight=balanced, clf__solver=lbfgs; total time=   2.5s
[CV] END clf__C=0.01, clf__class_weight=balanced, clf__solver=lbfgs; total time=   2.6s
[CV] END clf__C=0.01, clf__class_weight=None, clf__solver=lbfgs; total time=   2.8s
[CV] END clf__C=0.01, clf__class_weight=None, clf__solver=lbfgs; total time=   3.1s
[CV] END clf__C=0.01, clf__class_weight=None, clf__solver=lbfgs; total time=   3.1s
[CV] END clf__C=0.01, clf__class_weight=None, clf__solver=lbfgs; total time=   3.4s
[CV] END clf__C=0.01, clf__class_weight=None, clf__solver=saga; total time=   3.6s
[CV] END clf__C=0.01, clf__class_weight=None, clf__solver=saga; total time=   3.6s
[CV] END clf__C=0.01, clf__class_weight=None, clf__solver=saga; total time=   3.5s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced, clf__solver=lbfgs; total time=   2.2s
[CV] END clf__C=0.01, clf__class_weight=balanced, clf__solver=saga; total time=   4.4s
[CV] END clf__C=0.01, clf__class_weight=balanced, clf__solver=saga; total time=   4.7s
[CV] END clf__C=0.01, clf__class_weight=balanced, clf__solver=saga; total time=   4.7s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced, clf__solver=lbfgs; total time=   2.4s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced, clf__solver=lbfgs; total time=   2.9s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced, clf__solver=lbfgs; total time=   2.5s
[CV] END clf__C=0.01, clf__class_weight=None, clf__solver=saga; total time=   4.9s
[CV] END clf__C=0.01, clf__class_weight=balanced, clf__solver=saga; total time=   5.3s
[CV] END clf__C=0.03162277660168379, clf__class_weight=None, clf__solver=lbfgs; total time=   3.8s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced, clf__solver=saga; total time=   4.6s
[CV] END clf__C=0.03162277660168379, clf__class_weight=None, clf__solver=lbfgs; total time=   3.9s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced, clf__solver=saga; total time=   5.1s
[CV] END clf__C=0.03162277660168379, clf__class_weight=None, clf__solver=lbfgs; total time=   3.8s
[CV] END clf__C=0.03162277660168379, clf__class_weight=None, clf__solver=saga; total time=   3.8s
[CV] END clf__C=0.03162277660168379, clf__class_weight=None, clf__solver=saga; total time=   3.3s
[CV] END clf__C=0.03162277660168379, clf__class_weight=None, clf__solver=lbfgs; total time=   4.6s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced, clf__solver=saga; total time=   5.1s
[CV] END clf__C=0.03162277660168379, clf__class_weight=balanced, clf__solver=saga; total time=   5.5s
[CV] END clf__C=0.03162277660168379, clf__class_weight=None, clf__solver=saga; total time=   4.4s
[CV] END clf__C=0.03162277660168379, clf__class_weight=None, clf__solver=saga; total time=   4.3s
[CV] END clf__C=0.1, clf__class_weight=balanced, clf__solver=lbfgs; total time=   4.9s
[CV] END clf__C=0.1, clf__class_weight=balanced, clf__solver=lbfgs; total time=   4.6s
[CV] END clf__C=0.1, clf__class_weight=balanced, clf__solver=lbfgs; total time=   4.8s
[CV] END clf__C=0.1, clf__class_weight=balanced, clf__solver=lbfgs; total time=   5.2s
[CV] END clf__C=0.1, clf__class_weight=None, clf__solver=saga; total time=   3.7s
[CV] END clf__C=0.1, clf__class_weight=None, clf__solver=saga; total time=   4.4s
[CV] END clf__C=0.1, clf__class_weight=None, clf__solver=saga; total time=   4.1s
[CV] END clf__C=0.1, clf__class_weight=None, clf__solver=saga; total time=   4.6s
[CV] END clf__C=0.1, clf__class_weight=None, clf__solver=lbfgs; total time=   5.6s
[CV] END clf__C=0.1, clf__class_weight=None, clf__solver=lbfgs; total time=   6.4s
[CV] END clf__C=0.1, clf__class_weight=None, clf__solver=lbfgs; total time=   6.4s
[CV] END clf__C=0.1, clf__class_weight=balanced, clf__solver=saga; total time=   7.5s
[CV] END clf__C=0.1, clf__class_weight=balanced, clf__solver=saga; total time=   8.0s
[CV] END clf__C=0.1, clf__class_weight=None, clf__solver=lbfgs; total time=   7.8s
[CV] END clf__C=0.1, clf__class_weight=balanced, clf__solver=saga; total time=  10.0s
[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced, clf__solver=lbfgs; total time=   9.6s
[CV] END clf__C=0.31622776601683794, clf__class_weight=None, clf__solver=saga; total time=   3.9s
[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced, clf__solver=lbfgs; total time=  10.8s
[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced, clf__solver=lbfgs; total time=  10.5s
[CV] END clf__C=0.31622776601683794, clf__class_weight=None, clf__solver=saga; total time=   3.5s
[CV] END clf__C=0.31622776601683794, clf__class_weight=None, clf__solver=saga; total time=   5.0s
[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced, clf__solver=lbfgs; total time=  11.4s
[CV] END clf__C=0.31622776601683794, clf__class_weight=None, clf__solver=lbfgs; total time=   8.2s
[CV] END clf__C=0.1, clf__class_weight=balanced, clf__solver=saga; total time=  14.7s
[CV] END clf__C=0.31622776601683794, clf__class_weight=None, clf__solver=lbfgs; total time=   8.0s
[CV] END clf__C=0.31622776601683794, clf__class_weight=None, clf__solver=saga; total time=   3.9s
[CV] END clf__C=0.31622776601683794, clf__class_weight=None, clf__solver=lbfgs; total time=  10.9s
[CV] END clf__C=0.31622776601683794, clf__class_weight=None, clf__solver=lbfgs; total time=  11.1s
[CV] END clf__C=1.0, clf__class_weight=balanced, clf__solver=lbfgs; total time=  13.8s
[CV] END clf__C=1.0, clf__class_weight=balanced, clf__solver=lbfgs; total time=  12.9s
[CV] END clf__C=1.0, clf__class_weight=balanced, clf__solver=lbfgs; total time=  13.5s
[CV] END clf__C=1.0, clf__class_weight=balanced, clf__solver=lbfgs; total time=  13.8s
[CV] END clf__C=1.0, clf__class_weight=None, clf__solver=lbfgs; total time=  12.7s
[CV] END clf__C=1.0, clf__class_weight=None, clf__solver=lbfgs; total time=  12.5s
[CV] END clf__C=1.0, clf__class_weight=None, clf__solver=saga; total time=   3.7s
[CV] END clf__C=1.0, clf__class_weight=None, clf__solver=lbfgs; total time=  12.3s
[CV] END clf__C=1.0, clf__class_weight=None, clf__solver=saga; total time=   4.3s
[CV] END clf__C=1.0, clf__class_weight=None, clf__solver=saga; total time=   4.2s
[CV] END clf__C=1.0, clf__class_weight=None, clf__solver=saga; total time=   4.5s
[CV] END clf__C=1.0, clf__class_weight=None, clf__solver=lbfgs; total time=  15.8s
[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced, clf__solver=lbfgs; total time=  12.7s
[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced, clf__solver=lbfgs; total time=  15.5s
[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced, clf__solver=lbfgs; total time=  17.9s
[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced, clf__solver=lbfgs; total time=  18.1s
[CV] END clf__C=3.1622776601683795, clf__class_weight=None, clf__solver=lbfgs; total time=  15.8s
[CV] END clf__C=3.1622776601683795, clf__class_weight=None, clf__solver=lbfgs; total time=  12.5s
[CV] END clf__C=3.1622776601683795, clf__class_weight=None, clf__solver=lbfgs; total time=  17.3s
[CV] END clf__C=3.1622776601683795, clf__class_weight=None, clf__solver=lbfgs; total time=  16.4s
[CV] END clf__C=3.1622776601683795, clf__class_weight=None, clf__solver=saga; total time=  11.3s
[CV] END clf__C=3.1622776601683795, clf__class_weight=None, clf__solver=saga; total time=  12.4s
[CV] END clf__C=3.1622776601683795, clf__class_weight=None, clf__solver=saga; total time=  18.6s
[CV] END clf__C=3.1622776601683795, clf__class_weight=None, clf__solver=saga; total time=  15.9s
[CV] END clf__C=10.0, clf__class_weight=balanced, clf__solver=lbfgs; total time=  15.6s
[CV] END clf__C=10.0, clf__class_weight=balanced, clf__solver=lbfgs; total time=  17.4s
[CV] END clf__C=10.0, clf__class_weight=balanced, clf__solver=lbfgs; total time=  14.3s
[CV] END clf__C=10.0, clf__class_weight=balanced, clf__solver=lbfgs; total time=  22.2s

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=1.0, clf__class_weight=balanced, clf__solver=saga; total time= 1.8min

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced, clf__solver=saga; total time= 2.0min

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced, clf__solver=saga; total time= 2.1min

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced, clf__solver=saga; total time= 1.8min
[CV] END clf__C=10.0, clf__class_weight=None, clf__solver=lbfgs; total time=  11.9s

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=1.0, clf__class_weight=balanced, clf__solver=saga; total time= 2.1min

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=1.0, clf__class_weight=balanced, clf__solver=saga; total time= 2.1min
[CV] END clf__C=10.0, clf__class_weight=None, clf__solver=lbfgs; total time=  14.9s
[CV] END clf__C=10.0, clf__class_weight=None, clf__solver=lbfgs; total time=  13.4s

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=10.0, clf__class_weight=None, clf__solver=lbfgs; total time=  19.3s
[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced, clf__solver=saga; total time= 2.4min

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=1.0, clf__class_weight=balanced, clf__solver=saga; total time= 2.3min
[CV] END clf__C=0.31622776601683794, clf__class_weight=balanced, clf__solver=saga; total time= 2.5min
[CV] END clf__C=10.0, clf__class_weight=None, clf__solver=saga; total time=  16.5s
[CV] END clf__C=10.0, clf__class_weight=None, clf__solver=saga; total time=  14.9s

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced, clf__solver=saga; total time= 2.1min
[CV] END clf__C=10.0, clf__class_weight=None, clf__solver=saga; total time=  15.5s

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=10.0, clf__class_weight=None, clf__solver=saga; total time=  16.0s
[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced, clf__solver=saga; total time= 2.1min

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=3.1622776601683795, clf__class_weight=balanced, clf__solver=saga; total time= 2.1min

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=10.0, clf__class_weight=balanced, clf__solver=saga; total time= 1.2min

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=10.0, clf__class_weight=balanced, clf__solver=saga; total time= 1.2min

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=10.0, clf__class_weight=balanced, clf__solver=saga; total time= 1.3min

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV] END clf__C=10.0, clf__class_weight=balanced, clf__solver=saga; total time= 1.2min

=== Rodando GridSearchCV para RandomForest ===
Fitting 4 folds for each of 27 candidates, totalling 108 fits
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=200; total time=   4.0s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=200; total time=   4.3s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=200; total time=   4.3s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=200; total time=   4.6s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=500; total time=   8.8s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=500; total time=   8.8s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=500; total time=   8.9s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=500; total time=   9.0s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=200; total time=   9.2s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=200; total time=   9.3s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=200; total time=   9.5s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=200; total time=  11.0s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=800; total time=  13.7s

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=800; total time=  14.4s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=800; total time=  15.4s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=10, clf__n_estimators=800; total time=  15.6s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=500; total time=  21.7s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=200; total time=  16.4s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=200; total time=  17.0s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=500; total time=  22.5s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=200; total time=  17.2s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=500; total time=  23.0s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=500; total time=  25.2s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=200; total time=  19.3s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=200; total time=   3.1s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=200; total time=   3.5s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=200; total time=   3.3s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=200; total time=   4.9s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=500; total time=   6.9s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=500; total time=   7.9s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=800; total time=  32.4s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=500; total time=   7.8s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=500; total time=   7.9s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=800; total time=  37.5s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=800; total time=  37.3s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=20, clf__n_estimators=800; total time=  38.5s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=800; total time=  10.4s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=800; total time=  11.9s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=800; total time=  12.1s
[CV] END clf__class_weight=balanced, clf__max_depth=10, clf__n_estimators=800; total time=  11.3s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=200; total time=   9.3s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=500; total time=  42.9s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=200; total time=  10.3s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=200; total time=  10.3s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=200; total time=  13.6s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=500; total time=  48.3s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=500; total time=  18.9s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=500; total time=  56.4s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=500; total time=  21.6s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=500; total time=  58.1s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=500; total time=  24.3s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=500; total time=  28.2s
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=200; total time=  19.3s
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=200; total time=  19.3s
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=200; total time=  16.7s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=800; total time=  33.8s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=800; total time= 1.1min
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=800; total time= 1.1min
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=200; total time=  20.3s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=800; total time=  36.8s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=800; total time=  36.4s
[CV] END clf__class_weight=balanced, clf__max_depth=20, clf__n_estimators=800; total time=  37.1s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=200; total time=   3.8s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=200; total time=   3.5s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=200; total time=   3.2s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=200; total time=   3.3s
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=800; total time= 1.2min
[CV] END clf__class_weight=balanced_subsample, clf__max_depth=30, clf__n_estimators=800; total time= 1.2min
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=500; total time=   6.9s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=500; total time=   7.0s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=500; total time=   7.6s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=500; total time=   7.5s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=800; total time=  10.2s
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=200; total time=   7.5s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=800; total time=  11.8s
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=200; total time=   8.6s
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=500; total time=  36.6s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=800; total time=  11.8s
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=200; total time=   9.7s
[CV] END clf__class_weight=None, clf__max_depth=10, clf__n_estimators=800; total time=  12.9s
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=200; total time=   9.5s
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=500; total time=  43.5s
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=500; total time=  44.8s
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=500; total time=  17.7s
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=500; total time=  45.3s
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=500; total time=  19.5s
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=500; total time=  19.1s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=200; total time=  14.6s
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=500; total time=  21.3s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=200; total time=  14.3s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=200; total time=  17.1s
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=800; total time=  29.6s
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=800; total time=  28.5s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=200; total time=  16.4s
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=800; total time= 1.1min
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=800; total time= 1.1min
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=800; total time=  33.5s
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=800; total time= 1.1min
[CV] END clf__class_weight=None, clf__max_depth=20, clf__n_estimators=800; total time=  34.9s
[CV] END clf__class_weight=balanced, clf__max_depth=30, clf__n_estimators=800; total time= 1.1min
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=500; total time=  29.5s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=500; total time=  29.1s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=500; total time=  30.6s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=500; total time=  31.1s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=800; total time=  40.2s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=800; total time=  40.6s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=800; total time=  38.3s
[CV] END clf__class_weight=None, clf__max_depth=30, clf__n_estimators=800; total time=  40.1s

=== Rodando GridSearchCV para NaiveBayes ===
Fitting 4 folds for each of 9 candidates, totalling 36 fits
[CV] END ....................................clf__alpha=0.01; total time=   0.7s
[CV] END ....................................clf__alpha=0.01; total time=   0.8s
[CV] END ....................................clf__alpha=0.01; total time=   0.8s
[CV] END ....................................clf__alpha=0.01; total time=   0.8s
[CV] END ....................clf__alpha=0.023713737056616554; total time=   0.9s
[CV] END ....................clf__alpha=0.023713737056616554; total time=   0.8s
[CV] END ....................clf__alpha=0.023713737056616554; total time=   0.8s
[CV] END ....................clf__alpha=0.023713737056616554; total time=   0.9s
[CV] END .....................clf__alpha=0.31622776601683794; total time=   0.9s
[CV] END .....................clf__alpha=0.31622776601683794; total time=   0.9s
[CV] END .....................clf__alpha=0.31622776601683794; total time=   0.9s
[CV] END ......................clf__alpha=0.7498942093324559; total time=   0.9s
[CV] END ......................clf__alpha=0.7498942093324559; total time=   0.9s
[CV] END ......................clf__alpha=0.7498942093324559; total time=   0.9s
[CV] END ......................clf__alpha=0.7498942093324559; total time=   1.0s
[CV] END .....................clf__alpha=0.31622776601683794; total time=   1.3s
[CV] END ......................clf__alpha=1.7782794100389228; total time=   0.9s
[CV] END ......................clf__alpha=1.7782794100389228; total time=   0.8s
[CV] END ......................clf__alpha=1.7782794100389228; total time=   0.9s
[CV] END ......................clf__alpha=1.7782794100389228; total time=   1.2s
[CV] END .....................clf__alpha=0.05623413251903491; total time=   1.0s
[CV] END .......................clf__alpha=4.216965034285822; total time=   0.8s
[CV] END .....................clf__alpha=0.05623413251903491; total time=   0.9s
[CV] END .....................clf__alpha=0.05623413251903491; total time=   1.1s
[CV] END ......................clf__alpha=0.1333521432163324; total time=   0.8s
[CV] END .......................clf__alpha=4.216965034285822; total time=   1.1s
[CV] END .......................clf__alpha=4.216965034285822; total time=   0.9s
[CV] END ......................clf__alpha=0.1333521432163324; total time=   1.1s
[CV] END .......................clf__alpha=4.216965034285822; total time=   0.9s
[CV] END .....................clf__alpha=0.05623413251903491; total time=   0.8s
[CV] END ......................clf__alpha=0.1333521432163324; total time=   0.7s
[CV] END ......................clf__alpha=0.1333521432163324; total time=   0.7s
[CV] END ....................................clf__alpha=10.0; total time=   0.6s
[CV] END ....................................clf__alpha=10.0; total time=   0.6s
[CV] END ....................................clf__alpha=10.0; total time=   0.6s
[CV] END ....................................clf__alpha=10.0; total time=   0.6s

# One-stage Pipeline

## Classics

In [ ]:
import pandas as pd
import numpy as np
import os

from sklearn import clone
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

# ========= constants =========
CACHE_DIR = "cache_dir"
os.makedirs(CACHE_DIR, exist_ok=True)

RESULTS_DIR = "results/one-stage"
os.makedirs(RESULTS_DIR, exist_ok=True)

# ========= data =========
df_train = pd.read_parquet(f"./datasets/divided/train.parquet")
df_val = pd.read_parquet(f"./datasets/divided/val.parquet")

df_train = pd.concat([df_train, df_val], ignore_index=True)

df_test = pd.read_parquet("datasets/divided/test.parquet")

X_train = df_train["texto_lem"]
y_train = df_train["topico"]

X_test = df_test["texto_lem"]
y_test = df_test["topico"]

# ========= define models =========
MODELS = {
    "svc": LinearSVC(C=0.316, class_weight="balanced", random_state=42),
    "lr": LogisticRegression(
        C=10.0, class_weight="balanced", solver="lbfgs", random_state=42, max_iter=1000
    ),
    "rf": RandomForestClassifier(
        n_estimators=500,
        class_weight="balanced_subsample",
        max_depth=30,
        random_state=42,
        n_jobs=-1,
    ),
    "nb": MultinomialNB(alpha=0.01),
}

# ========= base pipeline =========
base_pipeline = Pipeline(
    [
        (
            "tfidf",
            TfidfVectorizer(
                max_features=None, ngram_range=(1, 2), min_df=3, max_df=0.8
            ),
        ),
        ("chi2", SelectKBest(chi2, k=20000)),
        ("clf", None),
    ],
    memory=CACHE_DIR,
)


# =========  helpers =========
def evaluate_model(modelo, nome_modelo, pipeline_base):
    print(f"\n=== Treinando e avaliando modelo: {nome_modelo} ===")
    # Clona o pipeline para garantir isolamento
    local_pipeline = clone(pipeline_base)
    local_pipeline.set_params(clf=modelo)

    # Treino e Predição
    local_pipeline.fit(X_train, y_train)
    y_pred = local_pipeline.predict(X_test)
    y_true = y_test

    print(classification_report(y_true, y_pred, digits=3, zero_division=0))

    # Retorna métricas
    return {
        "model": nome_modelo,
        "Accuracy": np.round(accuracy_score(y_true, y_pred), 3),
        "F1 Macro": np.round(f1_score(y_true, y_pred, average="macro"), 3),
        "F1 Weighted": np.round(f1_score(y_true, y_pred, average="weighted"), 3),
        "Recall Macro": np.round(recall_score(y_true, y_pred, average="macro"), 3),
        "Precision Macro": np.round(
            precision_score(y_true, y_pred, average="macro", zero_division=0), 3
        ),
        "preds": y_pred,
    }


# ========= evaluate models =========
results = []
for model_name, model in MODELS.items():
    results.append(evaluate_model(model, model_name, base_pipeline))

# ========= results consolidation =========
df_results = pd.DataFrame(results)

# metrics
df_metrics = df_results.drop(columns=["preds"])
df_metrics = df_metrics.sort_values(by="F1 Macro", ascending=False)

# predictions
dict_preds = {item["model"]: item["preds"] for item in results}
df_preds = pd.DataFrame(dict_preds)
df_preds["y_true"] = y_test

# ========= save to csv =========
df_metrics.to_csv(f"{RESULTS_DIR}/classics-results.csv", index=False)
df_preds.to_csv(f"{RESULTS_DIR}/classics-predictions.csv", index=False)

=== Treinando e avaliando modelo: svc ===
                                                    precision    recall  f1-score   support

                      América Latina Contemporânea      0.600     0.346     0.439        26
                            América Pré-Colombiana      0.538     1.000     0.700         7
              Análise Combinatória e Probabilidade      0.740     0.787     0.763        47
                                         Arcadismo      0.833     0.833     0.833         6
                    Aritmética e Matemática Básica      0.579     0.282     0.379        39
                           Arquitetura e Escultura      0.250     0.333     0.286         6
                               Arte Antiga e Média      0.000     0.000     0.000        11
                                Arte Contemporânea      0.105     0.167     0.129        12
                                      Arte Moderna      0.778     0.583     0.667        24
                Arte do Renascimento ao Romantismo      0.286     0.364     0.320        11
                                   Arte pelo Mundo      0.000     0.000     0.000        12
                                       Bacterioses      0.455     0.625     0.526         8
                                           Barroco      0.667     0.750     0.706         8
                                        Bioquímica      0.667     0.647     0.657        34
                                     Biotecnologia      0.556     0.556     0.556         9
                                          Botânica      0.656     0.600     0.627        35
                                    Brasil Colônia      0.898     0.823     0.859        96
                                    Brasil Império      0.840     0.829     0.834        82
                                  Brasil República      0.920     0.880     0.900        92
                                       Cartografia      0.333     1.000     0.500         6
                              Cidadania e Política      0.267     0.308     0.286        13
                                        Cinemática      0.660     0.717     0.688        46
                                         Citologia      0.882     0.789     0.833        38
          Colonização e Independência das Américas      0.450     0.818     0.581        11
                               Cultura e Sociedade      0.143     0.143     0.143         7
                    Desigualdade e Exclusão Social      0.375     0.500     0.429         6
                                          Dinâmica      0.667     0.621     0.643        29
                     Doenças Genéticas e Síndromes      0.667     0.629     0.647        35
                                          Ecologia      0.650     0.491     0.559        53
                                   Educação Física      0.385     0.833     0.526         6
                                      Eletricidade      0.857     0.947     0.900        38
                                  Eletromagnetismo      0.571     0.615     0.593        13
                                     Eletroquímica      0.765     0.929     0.839        14
                                       Embriologia      0.636     0.875     0.737        16
                                          Espanhol      0.818     1.000     0.900         9
           Estatística e Interpretação de Gráficos      0.483     0.636     0.549        22
                         Estequiometria e Cálculos      0.462     0.706     0.558        17
                                       Estilística      0.625     0.500     0.556        20
                                 Estrutura Atômica      0.611     0.917     0.733        12
                                          Estática      0.538     0.778     0.636         9
                                          Evolução      0.400     0.462     0.429        13
Expansão Marítima e Formação dos Estados Nacionais      0.200     0.200     0.200         5
                                  Filosofia Antiga      0.781     0.781     0.781        32
                           Filosofia Contemporânea      0.593     0.762     0.667        21
                                Filosofia Medieval      1.000     0.750     0.857         4
                                 Filosofia Moderna      0.614     0.750     0.675        36
                                Filosofia Temática      0.556     0.135     0.217        37
                                        Fisiologia      0.657     0.523     0.582        44
                   Formação dos EUA e Imperialismo      0.400     0.500     0.444         4
                         Fundamentos da Sociologia      0.600     0.667     0.632         9
                                            Fungos      0.143     1.000     0.250         1
                                           Funções      0.786     0.407     0.537        27
                                    Física Moderna      0.545     0.750     0.632         8
                                    Físico-Química      0.860     0.683     0.761        63
                                             Gases      0.500     0.600     0.545        15
                                          Genética      0.714     0.698     0.706        43
                               Geografia Ambiental      0.357     0.312     0.333        16
                               Geografia Econômica      0.000     0.000     0.000         4
                                  Geografia Física      0.680     0.607     0.642        28
                                  Geografia Urbana      0.250     0.222     0.235         9
                               Geometria Analítica      0.720     0.783     0.750        23
                      Geometria Espacial e Sólidos      0.682     0.857     0.759        35
                                   Geometria Plana      0.660     0.673     0.667        52
                         Geopolítica e Atualidades      0.857     1.000     0.923         6
                                         Gramática      0.455     0.455     0.455        11
                              Grandezas e Unidades      0.250     0.250     0.250         4
                                        Gravitação      0.600     0.800     0.686        15
                                     Grécia Antiga      0.714     0.714     0.714        14
                        Guerra Fria e Globalização      0.759     0.759     0.759        29
                                  Guerras Mundiais      0.789     0.682     0.732        22
                                      Hidrostática      0.786     0.917     0.846        12
                                        Histologia      0.630     0.654     0.642        26
                             Idade Antiga Oriental      0.571     1.000     0.727        12
               Idade Moderna: Revoluções e Reforma      0.438     0.538     0.483        13
                                       Idade Média      0.857     0.894     0.875        47
                                            Inglês      1.000     1.000     1.000        23
                                     Interpretação      0.424     0.311     0.359        45
                                 Ligações Químicas      0.600     0.857     0.706        14
                             Linguagens Artísticas      0.167     0.167     0.167         6
                               Literatura Africana      0.875     1.000     0.933         7
                          Literatura Contemporânea      0.625     0.417     0.500        12
                               Literatura Medieval      0.727     0.889     0.800         9
                             Matemática Financeira      0.312     1.000     0.476         5
                                     Meio Ambiente      0.400     0.632     0.490        19
                                        Modernismo      0.855     0.736     0.791        72
                                        Morfologia      0.500     0.714     0.588         7
                                    Música e Dança      0.483     0.667     0.560        21
                                 Números Complexos      0.500     0.750     0.600         4
                                       Ondulatória      0.690     0.935     0.795        31
                        Parnasianismo e Simbolismo      0.615     0.800     0.696        10
                  População e Dinâmica Demográfica      0.500     0.600     0.545        10
                                      Procariontes      0.200     0.286     0.235         7
                          Progressões e Sequências      0.579     0.647     0.611        17
                                         Protistas      0.364     0.571     0.444         7
                                       Protozooses      0.400     0.571     0.471         7
                                      Pré-História      0.467     0.700     0.560        10
                                      Quinhentismo      0.889     0.727     0.800        11
                                     Química Geral      0.429     0.162     0.235        37
                                Química Inorgânica      0.613     0.704     0.655        27
                                  Química Orgânica      0.833     0.726     0.776        62
                                    Radioatividade      0.385     0.714     0.500         7
                    Razão, Proporção e Porcentagem      0.417     0.169     0.241        59
                            Realismo e Naturalismo      0.667     0.857     0.750        21
                                 Regiões do Brasil      0.538     0.583     0.560        12
                       Reinos e Impérios Africanos      0.800     0.667     0.727         6
                            Revoluções Industriais      0.625     0.833     0.714         6
                                       Roma Antiga      1.000     0.750     0.857        12
                                        Romantismo      0.714     0.769     0.741        13
                                     Saúde Pública      0.000     0.000     0.000         4
                                           Sintaxe      0.333     0.600     0.429         5
                                  Sociolinguística      0.389     0.467     0.424        15
           Século XIX: Nacionalismo e Imperialismo      0.692     0.600     0.643        15
                                         Taxonomia      0.571     0.571     0.571         7
                                            Teatro      0.429     0.750     0.545         4
                                     Termodinâmica      0.154     0.400     0.222         5
                                        Termologia      0.800     0.667     0.727        36
                              Trabalho e Sociedade      0.538     0.636     0.583        11
                                     Trigonometria      0.625     0.417     0.500        12
                                         Virologia      0.222     0.500     0.308         4
                                           Viroses      0.750     0.750     0.750        16
                                          Zoologia      0.806     0.568     0.667        44
                         Álgebra Linear e Matrizes      0.706     0.750     0.727        16
                                Álgebra e Equações      0.765     0.667     0.712        39
                                            Óptica      0.833     0.897     0.864        39

                                          accuracy                          0.653      2613
                                         macro avg      0.568     0.630     0.580      2613
                                      weighted avg      0.666     0.653     0.647      2613


=== Treinando e avaliando modelo: lr ===
                                                    precision    recall  f1-score   support

                      América Latina Contemporânea      0.684     0.500     0.578        26
                            América Pré-Colombiana      0.538     1.000     0.700         7
              Análise Combinatória e Probabilidade      0.780     0.830     0.804        47
                                         Arcadismo      0.833     0.833     0.833         6
                    Aritmética e Matemática Básica      0.400     0.359     0.378        39
                           Arquitetura e Escultura      0.250     0.333     0.286         6
                               Arte Antiga e Média      0.000     0.000     0.000        11
                                Arte Contemporânea      0.111     0.167     0.133        12
                                      Arte Moderna      0.696     0.667     0.681        24
                Arte do Renascimento ao Romantismo      0.182     0.182     0.182        11
                                   Arte pelo Mundo      0.000     0.000     0.000        12
                                       Bacterioses      0.571     0.500     0.533         8
                                           Barroco      0.833     0.625     0.714         8
                                        Bioquímica      0.657     0.676     0.667        34
                                     Biotecnologia      0.571     0.444     0.500         9
                                          Botânica      0.625     0.571     0.597        35
                                    Brasil Colônia      0.900     0.844     0.871        96
                                    Brasil Império      0.810     0.829     0.819        82
                                  Brasil República      0.848     0.913     0.880        92
                                       Cartografia      0.500     1.000     0.667         6
                              Cidadania e Política      0.250     0.308     0.276        13
                                        Cinemática      0.723     0.739     0.731        46
                                         Citologia      0.722     0.684     0.703        38
          Colonização e Independência das Américas      0.529     0.818     0.643        11
                               Cultura e Sociedade      0.000     0.000     0.000         7
                    Desigualdade e Exclusão Social      0.429     0.500     0.462         6
                                          Dinâmica      0.655     0.655     0.655        29
                     Doenças Genéticas e Síndromes      0.667     0.571     0.615        35
                                          Ecologia      0.630     0.547     0.586        53
                                   Educação Física      0.375     0.500     0.429         6
                                      Eletricidade      0.857     0.947     0.900        38
                                  Eletromagnetismo      0.889     0.615     0.727        13
                                     Eletroquímica      0.765     0.929     0.839        14
                                       Embriologia      0.778     0.875     0.824        16
                                          Espanhol      0.900     1.000     0.947         9
           Estatística e Interpretação de Gráficos      0.500     0.682     0.577        22
                         Estequiometria e Cálculos      0.400     0.588     0.476        17
                                       Estilística      0.643     0.450     0.529        20
                                 Estrutura Atômica      0.688     0.917     0.786        12
                                          Estática      0.667     0.667     0.667         9
                                          Evolução      0.471     0.615     0.533        13
Expansão Marítima e Formação dos Estados Nacionais      0.167     0.200     0.182         5
                                  Filosofia Antiga      0.733     0.688     0.710        32
                           Filosofia Contemporânea      0.520     0.619     0.565        21
                                Filosofia Medieval      1.000     0.500     0.667         4
                                 Filosofia Moderna      0.643     0.750     0.692        36
                                Filosofia Temática      0.333     0.189     0.241        37
                                        Fisiologia      0.531     0.591     0.559        44
                   Formação dos EUA e Imperialismo      0.500     0.250     0.333         4
                         Fundamentos da Sociologia      0.625     0.556     0.588         9
                                            Fungos      0.500     1.000     0.667         1
                                           Funções      0.650     0.481     0.553        27
                                    Física Moderna      0.500     0.625     0.556         8
                                    Físico-Química      0.843     0.683     0.754        63
                                             Gases      0.600     0.600     0.600        15
                                          Genética      0.646     0.721     0.681        43
                               Geografia Ambiental      0.200     0.188     0.194        16
                               Geografia Econômica      0.000     0.000     0.000         4
                                  Geografia Física      0.500     0.536     0.517        28
                                  Geografia Urbana      0.286     0.222     0.250         9
                               Geometria Analítica      0.750     0.652     0.698        23
                      Geometria Espacial e Sólidos      0.743     0.743     0.743        35
                                   Geometria Plana      0.569     0.712     0.632        52
                         Geopolítica e Atualidades      0.833     0.833     0.833         6
                                         Gramática      0.400     0.364     0.381        11
                              Grandezas e Unidades      0.000     0.000     0.000         4
                                        Gravitação      0.722     0.867     0.788        15
                                     Grécia Antiga      0.750     0.643     0.692        14
                        Guerra Fria e Globalização      0.733     0.759     0.746        29
                                  Guerras Mundiais      0.882     0.682     0.769        22
                                      Hidrostática      0.846     0.917     0.880        12
                                        Histologia      0.583     0.538     0.560        26
                             Idade Antiga Oriental      0.600     1.000     0.750        12
               Idade Moderna: Revoluções e Reforma      0.438     0.538     0.483        13
                                       Idade Média      0.840     0.894     0.866        47
                                            Inglês      1.000     0.957     0.978        23
                                     Interpretação      0.316     0.400     0.353        45
                                 Ligações Químicas      0.688     0.786     0.733        14
                             Linguagens Artísticas      0.250     0.333     0.286         6
                               Literatura Africana      0.857     0.857     0.857         7
                          Literatura Contemporânea      0.571     0.333     0.421        12
                               Literatura Medieval      0.889     0.889     0.889         9
                             Matemática Financeira      0.333     0.600     0.429         5
                                     Meio Ambiente      0.500     0.579     0.537        19
                                        Modernismo      0.826     0.792     0.809        72
                                        Morfologia      0.500     0.571     0.533         7
                                    Música e Dança      0.480     0.571     0.522        21

## Transformers

### Tokenization

In [ ]:
import pandas as pd
import os
from transformers import BertTokenizer

if (
    not os.path.exists("./datasets/divided/test_tokenized.parquet")
    or not os.path.exists("./datasets/divided/train_tokenized.parquet")
    or not os.path.exists("./datasets/divided/val_tokenized.parquet")
):
    # Dados
    df_train = pd.read_parquet("./datasets/divided/train.parquet")
    df_val = pd.read_parquet("./datasets/divided/val.parquet")
    df_test = pd.read_parquet("./datasets/divided/test.parquet")

    dfs = {
        "train": df_train,
        "val": df_val,
        "test": df_test,
    }

    # Tokenização
    special_tokens = [
        "<num>",
        "<url>",
        "<delta>",
        "<graus>",
        "<raiz>",
        "<pi>",
        "<ohm>",
        "<lambda>",
        "<theta>",
        "<mu>",
        "<soma>",
    ]
    tokenizer = BertTokenizer.from_pretrained(
        "adalbertojunior/distilbert-portuguese-cased"
    )
    tokenizer.add_special_tokens({"additional_special_tokens": special_tokens})
    tokenizer.save_pretrained("./tokenizer-custom")

    for name, df in dfs.items():
        print(f"Tokenizando {name} set...")

        encodings = tokenizer(
            df["texto_clean_cased"].tolist(),
            truncation=True,
            padding="max_length",
            max_length=365,
        )

        df["input_ids"] = encodings["input_ids"]
        df["attention_mask"] = encodings["attention_mask"]

        df = df[["id", "materia", "topico", "input_ids", "attention_mask"]]

        df.to_parquet(
            f"./datasets/divided/{name}_tokenized.parquet",
            index=False,
        )

        print(f"Tokenização {name} concluída.")
else:
    print("Tokenized datasets already available. Skipping...")

### Training and Evaluation

In [1]:
import pandas as pd
import torch
import os
import numpy as np

import torch.nn.functional as F

from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score
from sklearn.utils import compute_class_weight

from transformers import BertForSequenceClassification, BertTokenizer
from transformers import TrainingArguments, Trainer
from transformers import EarlyStoppingCallback

# ======== constants =========
RESULTS_DIR = "./results/one-stage"
os.makedirs(RESULTS_DIR, exist_ok=True)


# ======== helpers ========
class QuestoesDataset(torch.utils.data.Dataset):
    def __init__(self, df):
        self.input_ids = torch.tensor(df["input_ids"].tolist())
        self.attention_mask = torch.tensor(df["attention_mask"].tolist())
        self.labels = torch.tensor(df["label"].tolist())

    def __getitem__(self, idx):
        return {
            "input_ids": self.input_ids[idx],
            "attention_mask": self.attention_mask[idx],
            "labels": self.labels[idx],
        }

    def __len__(self):
        return len(self.labels)


def get_best_epoch_from_trainer(trainer: Trainer) -> float:
    metric_name = trainer.args.metric_for_best_model

    if not metric_name:
        metric_name = "loss"

    if not metric_name.startswith("eval_"):
        metric_name = f"eval_{metric_name}"

    best_metric_val = trainer.state.best_metric

    best_epoch = 0.0

    for log in trainer.state.log_history:
        if metric_name in log:
            if log[metric_name] == best_metric_val:
                best_epoch = log["epoch"]
                break

    return best_epoch


# ======== data ===========
train_df = pd.read_parquet(f"./datasets/divided/train_tokenized.parquet")
val_df = pd.read_parquet(f"./datasets/divided/val_tokenized.parquet")
test_df = pd.read_parquet(f"./datasets/divided/test_tokenized.parquet")
full_train = pd.concat([train_df, val_df], ignore_index=True)

train_df["label"] = train_df["topico"].astype("category").cat.codes

label2id = {
    v: k
    for k, v in dict(
        enumerate(train_df["topico"].astype("category").cat.categories)
    ).items()
}
id2label = dict(enumerate(train_df["topico"].astype("category").cat.categories))

val_df["label"] = val_df["topico"].map(label2id)
test_df["label"] = test_df["topico"].map(label2id)
full_train["label"] = full_train["topico"].map(label2id)



train_dataset = QuestoesDataset(train_df)
val_dataset = QuestoesDataset(val_df)
test_dataset = QuestoesDataset(test_df)
full_train_dataset = QuestoesDataset(full_train)

# ======== models ===========
MODELS = {
    # "distilbert": "adalbertojunior/distilbert-portuguese-cased",
    "bert": "neuralmind/bert-base-portuguese-cased",
}


# ======== custom metrics and loss ===========
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    acc = accuracy_score(labels, predictions)
    f1_macro = f1_score(labels, predictions, average="macro")
    f1_weighted = f1_score(labels, predictions, average="weighted")
    recall = recall_score(labels, predictions, average="macro", zero_division=0)
    precision = precision_score(labels, predictions, average="macro", zero_division=0)

    return {
        "accuracy": acc,
        "macro-precision": precision,
        "macro-recall": recall,
        "macro-f1": f1_macro,
        "weighted-f1": f1_weighted,
    }


# Cálculo dos pesos das classes
class_weights = compute_class_weight(
    class_weight="balanced", classes=np.unique(train_df["label"]), y=train_df["label"]
)

class_weights = torch.tensor(class_weights, dtype=torch.float)


def weighted_ce_loss(outputs, labels, num_items_in_batch: int):
    logits = outputs.logits
    weight = class_weights.to(logits.device)  # type: ignore
    return F.cross_entropy(logits, labels, weight=weight)


early_stopping_callback = EarlyStoppingCallback(
    early_stopping_threshold=0.005, early_stopping_patience=2
)

# ======== training args ===========
training_args = TrainingArguments(
    output_dir="./modelos-treinamento",  # Pasta para salvar o modelo
    eval_strategy="epoch",  # Avalia o modelo a cada época
    save_strategy="epoch",  # Salva o modelo a cada época
    save_total_limit=2,  # Mantém apenas os 2 últimos modelos salvos
    num_train_epochs=10,  # Número de épocas
    per_device_train_batch_size=12,  # Tamanho do batch de treino.
    per_device_eval_batch_size=24,  # Tamanho do batch de avaliação
    warmup_ratio=0.1,  # Passos de aquecimento do otimizador
    weight_decay=0.01,  # Regularização
    learning_rate=4e-5,  # Taxa de aprendizado
    load_best_model_at_end=True,  # Carrega o melhor modelo no final do treino
    metric_for_best_model="macro-f1",  # Usa a macro-f1 para decidir o melhor modelo
    logging_strategy="epoch",
)

# ======== preliminar training ===========
for model_name, model_path in MODELS.items():
    model = BertForSequenceClassification.from_pretrained(
        model_path,
        num_labels=len(id2label),
        id2label=id2label,
        label2id=label2id,
    )

    tokenizer = BertTokenizer.from_pretrained("./tokenizer-custom")
    model.resize_token_embeddings(len(tokenizer))

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
        compute_loss_func=weighted_ce_loss,
        callbacks=[early_stopping_callback],
    )

    print(f"\n=== Treinamento preliminar modelo: {model_name} ===")

    trainer.train()

    best_epoch = get_best_epoch_from_trainer(trainer)

    print(f"Best epoch for {model_name}: {best_epoch}")

    # ======== final training (refit) ===========
    print(f"\n=== Treinamento final modelo (refit): {model_name} ===")

    final_training_args = TrainingArguments(
        output_dir="./modelos-treinamento-final",  # Pasta para salvar o modelo
        num_train_epochs=best_epoch,  # Número de épocas baseado no melhor da prévia # type: ignore
        per_device_train_batch_size=12,  # Tamanho do batch de treino.
        per_device_eval_batch_size=24,  # Tamanho do batch de avaliação
        learning_rate=4e-5,
        weight_decay=0.01,
        warmup_ratio=0.1,
        save_strategy="no",  # Não precisa salvar checkpoints intermediários
        eval_strategy="no",  # Não avalia (não tem dataset de validação)
        logging_strategy="epoch",
    )

    final_trainer = Trainer(
        model=model,
        args=final_training_args,
        train_dataset=full_train_dataset,
        compute_metrics=compute_metrics,
        compute_loss_func=weighted_ce_loss,
    )

    final_trainer.train()

    # ======== evaluation ===========
    predictions = final_trainer.predict(test_dataset)
    predictions_label = np.argmax(predictions.predictions, axis=-1)

    metrics = compute_metrics((predictions.predictions, test_df["label"].to_numpy()))

    # ======== results consolidation ===========
    df_scores = pd.DataFrame(
        {name: value for name, value in metrics.items()}, index=[0]
    )
    print("\n=== Evaluation Scores ===")
    print(df_scores)

    df_preds = pd.DataFrame(
        {
            "y_true": test_df["label"],
            "y_pred": predictions_label,
        }
    )

    df_preds["y_true"] = df_preds["y_true"].map(id2label)
    df_preds["y_pred"] = df_preds["y_pred"].map(id2label)

    # ======== save to csv ===========
    df_scores.to_csv(
        f"{RESULTS_DIR}/{model_name}-results.csv",
        index=False,
    )

    df_preds.to_csv(
        f"{RESULTS_DIR}/{model_name}-predictions.csv",
        index=False,
    )

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`

=== Treinamento preliminar modelo: bert ===

Best epoch for bert: 6.0

=== Treinamento final modelo (refit): bert ===

=== Evaluation Scores ===
   accuracy  macro-precision  macro-recall  macro-f1  weighted-f1
0  0.666284         0.612292      0.609974  0.600179     0.664335

# Two-stage Pipeline

## First stage (subject)

### Classics

In [1]:
import pandas as pd
import numpy as np
import os

from sklearn import clone
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    accuracy_score,
    classification_report,
)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

# ========= constants =========
CACHE_DIR = "cache_dir"
os.makedirs(CACHE_DIR, exist_ok=True)

RESULTS_DIR = "results/two-stage/subject-classification"
os.makedirs(RESULTS_DIR, exist_ok=True)

# ========= data =========
df_train = pd.read_parquet(f"./datasets/divided/train.parquet")
df_val = pd.read_parquet(f"./datasets/divided/val.parquet")
df_test = pd.read_parquet("datasets/divided/test.parquet")

df_train = pd.concat([df_train, df_val], ignore_index=True)

X_train = df_train["texto_lem"]
y_train = df_train["materia"]

X_test = df_test["texto_lem"]
y_test = df_test["materia"]

# ========= define models =========
MODELS = {
    "svc": LinearSVC(C=0.316, class_weight="balanced", random_state=42),
    "lr": LogisticRegression(
        C=10.0, class_weight="balanced", solver="lbfgs", random_state=42, max_iter=1000
    ),
    "rf": RandomForestClassifier(
        n_estimators=500,
        class_weight="balanced_subsample",
        max_depth=30,
        random_state=42,
        n_jobs=-1,
    ),
    "nb": MultinomialNB(alpha=0.01),
}

# ========= base pipeline =========
base_pipeline = Pipeline(
    [
        (
            "tfidf",
            TfidfVectorizer(
                max_features=None, ngram_range=(1, 2), min_df=3, max_df=0.8
            ),
        ),
        ("chi2", SelectKBest(chi2, k=20000)),
        ("clf", None),
    ],
    memory=CACHE_DIR,
)


# =========  helpers =========
def evaluate_model(modelo, nome_modelo, pipeline_base):
    print(f"\n=== Treinando e avaliando modelo: {nome_modelo} ===")
    # Clona o pipeline para garantir isolamento
    local_pipeline = clone(pipeline_base)
    local_pipeline.set_params(clf=modelo)

    # Treino e Predição
    local_pipeline.fit(X_train, y_train)
    y_pred = local_pipeline.predict(X_test)
    y_true = y_test

    print(classification_report(y_true, y_pred, digits=3, zero_division=0))

    # Retorna métricas
    return {
        "model": nome_modelo,
        "Accuracy": np.round(accuracy_score(y_true, y_pred), 3),
        "F1 Macro": np.round(f1_score(y_true, y_pred, average="macro"), 3),
        "F1 Weighted": np.round(f1_score(y_true, y_pred, average="weighted"), 3),
        "Recall Macro": np.round(recall_score(y_true, y_pred, average="macro"), 3),
        "Precision Macro": np.round(
            precision_score(y_true, y_pred, average="macro", zero_division=0), 3
        ),
        "preds": y_pred,
    }


# ========= evaluate models =========
results = []
for model_name, model in MODELS.items():
    results.append(evaluate_model(model, model_name, base_pipeline))

# ========= results consolidation =========
df_results = pd.DataFrame(results)

# metrics
df_metrics = df_results.drop(columns=["preds"])
df_metrics = df_metrics.sort_values(by="F1 Macro", ascending=False)

# predictions
dict_preds = {item["model"]: item["preds"] for item in results}
df_preds = pd.DataFrame(dict_preds)
df_preds["y_true"] = y_test

# ========= save to csv =========
df_metrics.to_csv(f"{RESULTS_DIR}/classics-results.csv", index=False)
df_preds.to_csv(f"{RESULTS_DIR}/classics-predictions.csv", index=False)

=== Treinando e avaliando modelo: svc ===
              precision    recall  f1-score   support

       artes      0.750     0.785     0.767       107
    biologia      0.947     0.907     0.926       451
   filosofia      0.940     0.838     0.886       130
      fisica      0.905     0.914     0.910       292
   geografia      0.714     0.769     0.741        91
    historia      0.929     0.949     0.939       509
     idiomas      0.970     1.000     0.985        32
  literatura      0.899     0.893     0.896       169
  matematica      0.921     0.945     0.933       397
   portugues      0.737     0.771     0.753       109
     quimica      0.906     0.900     0.903       280
  sociologia      0.600     0.522     0.558        46

    accuracy                          0.896      2613
   macro avg      0.851     0.849     0.850      2613
weighted avg      0.896     0.896     0.896      2613


=== Treinando e avaliando modelo: lr ===
              precision    recall  f1-score   support

       artes      0.764     0.785     0.774       107
    biologia      0.938     0.911     0.925       451
   filosofia      0.932     0.838     0.883       130
      fisica      0.905     0.914     0.910       292
   geografia      0.676     0.758     0.715        91
    historia      0.925     0.941     0.933       509
     idiomas      0.968     0.938     0.952        32
  literatura      0.918     0.858     0.887       169
  matematica      0.921     0.940     0.930       397
   portugues      0.742     0.817     0.777       109
     quimica      0.906     0.900     0.903       280
  sociologia      0.659     0.587     0.621        46

    accuracy                          0.894      2613
   macro avg      0.854     0.849     0.851      2613
weighted avg      0.895     0.894     0.894      2613


=== Treinando e avaliando modelo: rf ===
              precision    recall  f1-score   support

       artes      0.694     0.720     0.706       107
    biologia      0.843     0.823     0.833       451
   filosofia      0.787     0.823     0.805       130
      fisica      0.878     0.815     0.845       292
   geografia      0.617     0.549     0.581        91
    historia      0.849     0.896     0.872       509
     idiomas      0.969     0.969     0.969        32
  literatura      0.794     0.799     0.796       169
  matematica      0.843     0.907     0.874       397
   portugues      0.574     0.606     0.589       109
     quimica      0.836     0.818     0.827       280
  sociologia      0.579     0.239     0.338        46

    accuracy                          0.816      2613
   macro avg      0.772     0.747     0.753      2613
weighted avg      0.813     0.816     0.813      2613


=== Treinando e avaliando modelo: nb ===
              precision    recall  f1-score   support

       artes      0.784     0.710     0.745       107
    biologia      0.938     0.940     0.939       451
   filosofia      0.926     0.862     0.892       130
      fisica      0.908     0.918     0.913       292
   geografia      0.741     0.659     0.698        91
    historia      0.882     0.967     0.922       509
     idiomas      0.970     1.000     0.985        32
  literatura      0.829     0.888     0.857       169
  matematica      0.966     0.922     0.943       397
   portugues      0.725     0.725     0.725       109
     quimica      0.908     0.914     0.911       280
  sociologia      0.720     0.391     0.507        46

    accuracy                          0.893      2613
   macro avg      0.858     0.825     0.836      2613
weighted avg      0.891     0.893     0.891      2613

### Transformers

In [ ]:
import torch
import os

import pandas as pd
import numpy as np

import torch.nn.functional as F

from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score
from sklearn.utils import compute_class_weight

from transformers import BertForSequenceClassification, BertTokenizer
from transformers import TrainingArguments, Trainer
from transformers import EarlyStoppingCallback

# ======== constants =========
RESULTS_DIR = "results/two-stage/subject-classification"
os.makedirs(RESULTS_DIR, exist_ok=True)


# ======== helpers ========
class QuestoesDataset(torch.utils.data.Dataset):
    def __init__(self, df):
        self.input_ids = torch.tensor(df["input_ids"].tolist())
        self.attention_mask = torch.tensor(df["attention_mask"].tolist())
        self.labels = torch.tensor(df["label"].tolist())

    def __getitem__(self, idx):
        return {
            "input_ids": self.input_ids[idx],
            "attention_mask": self.attention_mask[idx],
            "labels": self.labels[idx],
        }

    def __len__(self):
        return len(self.labels)


def get_best_epoch_from_trainer(trainer: Trainer) -> float:
    metric_name = trainer.args.metric_for_best_model

    if not metric_name:
        metric_name = "loss"

    if not metric_name.startswith("eval_"):
        metric_name = f"eval_{metric_name}"

    best_metric_val = trainer.state.best_metric

    best_epoch = 0.0

    for log in trainer.state.log_history:
        if metric_name in log:
            if log[metric_name] == best_metric_val:
                best_epoch = log["epoch"]
                break

    return best_epoch


# ======== data ===========
train_df = pd.read_parquet(f"./datasets/divided/train_tokenized.parquet")
val_df = pd.read_parquet(f"./datasets/divided/val_tokenized.parquet")
test_df = pd.read_parquet(f"./datasets/divided/test_tokenized.parquet")

train_df["label"] = train_df["materia"].astype("category").cat.codes

label2id = {
    v: k
    for k, v in dict(
        enumerate(train_df["materia"].astype("category").cat.categories)
    ).items()
}
id2label = dict(enumerate(train_df["materia"].astype("category").cat.categories))

val_df["label"] = val_df["materia"].map(label2id)
test_df["label"] = test_df["materia"].map(label2id)

full_train = pd.concat([train_df, val_df], ignore_index=True)


train_dataset = QuestoesDataset(train_df)
val_dataset = QuestoesDataset(val_df)
test_dataset = QuestoesDataset(test_df)
full_train_dataset = QuestoesDataset(full_train)

# ======== models ===========
MODELS = {
    "distilbert": "adalbertojunior/distilbert-portuguese-cased",
    "bert": "neuralmind/bert-base-portuguese-cased",
}


# ======== custom metrics and loss ===========
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    acc = accuracy_score(labels, predictions)
    f1_macro = f1_score(labels, predictions, average="macro")
    f1_weighted = f1_score(labels, predictions, average="weighted")
    recall = recall_score(labels, predictions, average="macro", zero_division=0)
    precision = precision_score(labels, predictions, average="macro", zero_division=0)

    return {
        "accuracy": acc,
        "macro-precision": precision,
        "macro-recall": recall,
        "macro-f1": f1_macro,
        "weighted-f1": f1_weighted,
    }


# Cálculo dos pesos das classes
class_weights = compute_class_weight(
    class_weight="balanced", classes=np.unique(train_df["label"]), y=train_df["label"]
)

class_weights = torch.tensor(class_weights, dtype=torch.float)


def weighted_ce_loss(outputs, labels, num_items_in_batch: int):
    logits = outputs.logits
    weight = class_weights.to(logits.device)  # type: ignore
    return F.cross_entropy(logits, labels, weight=weight)


early_stopping_callback = EarlyStoppingCallback(
    early_stopping_threshold=0.005, early_stopping_patience=2
)

# ======== training args ===========
training_args = TrainingArguments(
    output_dir="./modelos-treinamento",  # Pasta para salvar o modelo
    eval_strategy="epoch",  # Avalia o modelo a cada época
    save_strategy="epoch",  # Salva o modelo a cada época
    save_total_limit=2,  # Mantém apenas os 2 últimos modelos salvos
    num_train_epochs=10,  # Número de épocas
    per_device_train_batch_size=12,  # Tamanho do batch de treino.
    per_device_eval_batch_size=24,  # Tamanho do batch de avaliação
    warmup_ratio=0.1,  # Passos de aquecimento do otimizador
    weight_decay=0.01,  # Regularização
    learning_rate=4e-5,  # Taxa de aprendizado
    logging_strategy="epoch",
    load_best_model_at_end=True,  # Carrega o melhor modelo no final do treino
    metric_for_best_model="macro-f1",  # Usa a macro-f1 para decidir o melhor modelo
)

# ======== preliminar training ===========
for model_name, model_path in MODELS.items():
    model = BertForSequenceClassification.from_pretrained(
        model_path,
        num_labels=len(id2label),
        id2label=id2label,
        label2id=label2id,
    )

    tokenizer = BertTokenizer.from_pretrained("./tokenizer-custom")
    model.resize_token_embeddings(len(tokenizer))

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
        compute_loss_func=weighted_ce_loss,
        callbacks=[early_stopping_callback],
    )

    print(f"\n=== Treinamento preliminar modelo: {model_name} ===")

    trainer.train()

    best_epoch = get_best_epoch_from_trainer(trainer)

    print(f"Best epoch for {model_name}: {best_epoch}")

    # ======== final training (refit) ===========
    print(f"\n=== Treinamento final modelo (refit): {model_name} ===")

    final_training_args = TrainingArguments(
        output_dir="./modelos-treinamento-final",  # Pasta para salvar o modelo
        num_train_epochs=best_epoch,  # Número de épocas baseado no melhor da prévia # type: ignore
        per_device_train_batch_size=12,  # Tamanho do batch de treino.
        per_device_eval_batch_size=24,  # Tamanho do batch de avaliação
        learning_rate=4e-5,
        weight_decay=0.01,
        warmup_ratio=0.1,
        save_strategy="no",  # Não precisa salvar checkpoints intermediários
        eval_strategy="no",  # Não avalia (não tem dataset de validação)
        logging_strategy="epoch",
    )

    final_trainer = Trainer(
        model=model,
        args=final_training_args,
        train_dataset=full_train_dataset,
        compute_metrics=compute_metrics,
        compute_loss_func=weighted_ce_loss,
    )

    final_trainer.train()

    # ======== evaluation ===========
    predictions = final_trainer.predict(test_dataset)
    predictions_label = np.argmax(predictions.predictions, axis=-1)

    metrics = compute_metrics((predictions.predictions, test_df["label"].to_numpy()))

    # ======== results consolidation ===========
    df_scores = pd.DataFrame(
        {name: value for name, value in metrics.items()}, index=[0]
    )
    print("\n=== Evaluation Scores ===")
    print(df_scores)

    df_preds = pd.DataFrame(
        {
            "y_true": test_df["label"],
            "y_pred": predictions_label,
        }
    )

    df_preds["y_true"] = df_preds["y_true"].map(id2label)
    df_preds["y_pred"] = df_preds["y_pred"].map(id2label)

    # ======== save to csv ===========
    df_scores.to_csv(
        f"{RESULTS_DIR}/{model_name}-results.csv",
        index=False,
    )

    df_preds.to_csv(
        f"{RESULTS_DIR}/{model_name}-predictions.csv",
        index=False,
    )

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar modelo: distilbert ===

=== Treinamento preliminar concluído ===
Best epoch for distilbert: 6.0

=== Treinamento final modelo (refit): distilbert ===

=== Treinamento final concluído ===

=== Evaluation Scores ===
   accuracy  macro-precision  macro-recall  macro-f1  weighted-f1
0  0.907769         0.869718      0.854539   0.86096      0.90713

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar modelo: bert ===

=== Treinamento preliminar concluído ===
Best epoch for bert: 6.0

=== Treinamento final modelo (refit): bert ===

=== Treinamento final concluído ===

=== Evaluation Scores ===
   accuracy  macro-precision  macro-recall  macro-f1  weighted-f1
0  0.916954         0.887843      0.869741  0.877077     0.916234

## Second stage (topic)

### Classics

In [ ]:
import os
import pandas as pd

from concurrent.futures import ProcessPoolExecutor
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectPercentile, chi2
from sklearn.pipeline import Pipeline
from sklearn.base import clone
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    accuracy_score,
)

# ======== constants =========
RESULTS_DIR = "results/two-stage/topic-classification"
os.makedirs(RESULTS_DIR, exist_ok=True)

# ======== data ===========
df_train = pd.read_parquet(f"./datasets/divided/train.parquet")
df_val = pd.read_parquet(f"./datasets/divided/val.parquet")
df_test = pd.read_parquet("datasets/divided/test.parquet")

df_train = pd.concat([df_train, df_val], ignore_index=True)

bert_preds = pd.read_csv(
    "results/two-stage/subject-classification/bert-predictions.csv"
)

df_test["bert_pred_subject"] = bert_preds["y_pred"]

# ======== models and pipelines ===========
models = {
    "svc": LinearSVC(C=0.316, class_weight="balanced", random_state=42),
    "lr": LogisticRegression(
        C=10.0, class_weight="balanced", solver="lbfgs", random_state=42, max_iter=1000
    ),
    "rf": RandomForestClassifier(
        n_estimators=800,
        class_weight="balanced_subsample",
        max_depth=30,
        random_state=42,
    ),
    "nb": MultinomialNB(alpha=0.01),
}

vectorizer = TfidfVectorizer(
    max_features=None,
    ngram_range=(1, 3),
    min_df=3,
    max_df=0.8,
)

selector = SelectPercentile(chi2, percentile=30)

base_pipeline = Pipeline(
    [
        ("tfidf", vectorizer),
        ("chi2", selector),
        ("clf", None),
    ]
)

subjects = df_train["materia"].unique()


# ======== helpers ===========
def compute_metrics(y_true, y_pred):
    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "f1_macro": f1_score(y_true, y_pred, average="macro"),
        "f1_weighted": f1_score(y_true, y_pred, average="weighted"),
        "precision_macro": precision_score(
            y_true, y_pred, average="macro", zero_division=0
        ),
        "recall_macro": recall_score(y_true, y_pred, average="macro", zero_division=0),
    }


def flatten_metrics(metrics_dict, prefix):
    return {f"{prefix}_{k}": v for k, v in metrics_dict.items()}


def train_and_preds(name, model, materia):
    pipeline = clone(base_pipeline)
    pipeline.set_params(clf=model)

    # --- 1. Preparação dos Dados ---
    # Treino (filtrado por matéria)
    mask_train = df_train["materia"] == materia
    x_train = df_train[mask_train]["texto_lem"]
    y_train = df_train[mask_train]["topico"]

    # Teste Gold (Gabarito: Matéria Real == materia atual)
    mask_gold = df_test["materia"] == materia
    x_test_gold = df_test[mask_gold]["texto_lem"]
    y_test_gold = df_test[mask_gold]["topico"]
    ids_gold = df_test[mask_gold]["id"]  # <--- GUARDAMOS OS ÍNDICES ORIGINAIS

    # Teste Real (Pipeline: Predição do BERT == materia atual)
    mask_real = df_test["bert_pred_subject"] == materia
    x_test_real = df_test[mask_real]["texto_lem"]
    ids_real = df_test[mask_real]["id"]  # <--- GUARDAMOS OS ÍNDICES ORIGINAIS

    # --- 2. Treinamento ---
    pipeline.fit(x_train, y_train)

    # --- 3. Inferência ---

    # 3.2 Avaliação Gold
    df_preds_gold = pd.DataFrame()
    df_preds_gold["id"] = ids_gold
    df_preds_gold["subject_true"] = materia
    df_preds_gold["y_true"] = y_test_gold
    df_preds_gold["y_pred_gold"] = pipeline.predict(x_test_gold)

    # 3.1 Avaliação Real
    df_preds_real = pd.DataFrame()
    df_preds_real["id"] = ids_real
    df_preds_real["subject_bert"] = materia
    df_preds_real["y_pred_real"] = pipeline.predict(x_test_real)

    # Merge DFs
    df_preds_merged = pd.merge(
        df_preds_gold,
        df_preds_real,
        on=["id"],
        how="outer",
    )
    df_preds_merged["model"] = name

    return df_preds_merged


# ======== training execution ===========
tasks = []
preds_dfs = []

with ProcessPoolExecutor() as executor:
    # Dispara as tarefas
    for name, model in models.items():
        for subject in subjects:
            tasks.append(executor.submit(train_and_preds, name, model, subject))

    # Coleta os resultados
    for future in tasks:
        res = future.result()
        if res is not None:
            preds = res
            preds_dfs.append(preds)

# ======== saving ===========

df_final_results = pd.concat(preds_dfs, ignore_index=True)
df_consolidado = df_final_results.groupby(["id", "model"], as_index=False).first()
df_consolidado.to_csv(
    f"{RESULTS_DIR}/classics-predictions.csv",
    index=False,
)

print("Processamento concluído e arquivos salvos!")

Processamento concluído e arquivos salvos!

### Transformers

In [ ]:
import torch
import os

import pandas as pd
import numpy as np

import torch.nn.functional as F

from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score
from sklearn.utils import compute_class_weight

from transformers import BertForSequenceClassification, BertTokenizer
from transformers import TrainingArguments, Trainer
from transformers import EarlyStoppingCallback

# ======== constants =========
RESULTS_DIR = "results/two-stage/topic-classification"
os.makedirs(RESULTS_DIR, exist_ok=True)


# ======== helpers ========
class QuestoesDataset(torch.utils.data.Dataset):
    def __init__(self, df):
        self.input_ids = torch.tensor(df["input_ids"].tolist())
        self.attention_mask = torch.tensor(df["attention_mask"].tolist())
        self.labels = torch.tensor(df["label"].tolist())

    def __getitem__(self, idx):
        return {
            "input_ids": self.input_ids[idx],
            "attention_mask": self.attention_mask[idx],
            "labels": self.labels[idx],
        }

    def __len__(self):
        return len(self.labels)


def get_best_epoch_from_trainer(trainer: Trainer) -> float:
    metric_name = trainer.args.metric_for_best_model

    if not metric_name:
        metric_name = "loss"

    if not metric_name.startswith("eval_"):
        metric_name = f"eval_{metric_name}"

    best_metric_val = trainer.state.best_metric

    best_epoch = 0.0

    for log in trainer.state.log_history:
        if metric_name in log:
            if log[metric_name] == best_metric_val:
                best_epoch = log["epoch"]
                break

    return best_epoch


# ======== data ===========
df_train = pd.read_parquet(f"./datasets/divided/train_tokenized.parquet")
df_val = pd.read_parquet(f"./datasets/divided/val_tokenized.parquet")

df_test = pd.read_parquet(f"./datasets/divided/test_tokenized.parquet")
bert_preds = pd.read_csv(
    "results/two-stage/subject-classification/bert-predictions.csv"
)
df_test["bert_pred_subject"] = bert_preds["y_pred"]

# ======== models ===========
MODELS = {
    "distilbert": "adalbertojunior/distilbert-portuguese-cased",
    "bert": "neuralmind/bert-base-portuguese-cased",
}


# ======== custom metrics and loss ===========
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    acc = accuracy_score(labels, predictions)
    f1_macro = f1_score(labels, predictions, average="macro")
    f1_weighted = f1_score(labels, predictions, average="weighted")
    recall = recall_score(labels, predictions, average="macro", zero_division=0)
    precision = precision_score(labels, predictions, average="macro", zero_division=0)

    return {
        "accuracy": acc,
        "macro-precision": precision,
        "macro-recall": recall,
        "macro-f1": f1_macro,
        "weighted-f1": f1_weighted,
    }


early_stopping_callback = EarlyStoppingCallback(
    early_stopping_threshold=0.005, early_stopping_patience=4
)

# ======== training args ===========
training_args = TrainingArguments(
    output_dir="./modelos-treinamento",  # Pasta para salvar o modelo
    eval_strategy="epoch",  # Avalia o modelo a cada época
    save_strategy="epoch",  # Salva o modelo a cada época
    save_total_limit=2,  # Mantém apenas os 2 últimos modelos salvos
    num_train_epochs=20,  # Número de épocas
    per_device_train_batch_size=12,  # Tamanho do batch de treino.
    per_device_eval_batch_size=24,  # Tamanho do batch de avaliação
    warmup_ratio=0.1,  # Passos de aquecimento do otimizador
    weight_decay=0.01,  # Regularização
    learning_rate=3e-5,  # Taxa de aprendizado
    logging_strategy="epoch",
    load_best_model_at_end=True,  # Carrega o melhor modelo no final do treino
    metric_for_best_model="macro-f1",  # Usa a macro-f1 para decidir o melhor modelo
)

tokenizer = BertTokenizer.from_pretrained("./tokenizer-custom")

subjects = df_train["materia"].unique()


# ======== training and prediction function ===========
def train_preds(subject: str):
    # Filtra treino e validação pela matéria atual
    masked_train = df_train[df_train["materia"] == subject].copy()
    masked_val = df_val[df_val["materia"] == subject].copy()

    label2id = {
        v: k
        for k, v in dict(
            enumerate(masked_train["topico"].astype("category").cat.categories)
        ).items()
    }
    id2label = dict(enumerate(masked_train["topico"].astype("category").cat.categories))

    masked_train["label"] = masked_train["topico"].map(label2id)
    masked_val["label"] = masked_val["topico"].map(label2id)

    train_dataset = QuestoesDataset(masked_train)
    val_dataset = QuestoesDataset(masked_val)

    # peso das classes específico para a matéria
    class_weights = compute_class_weight(
        class_weight="balanced",
        classes=np.unique(masked_train["label"]),
        y=masked_train["label"],
    )
    class_weights = torch.tensor(class_weights, dtype=torch.float)

    def weighted_ce_loss(outputs, labels, num_items_in_batch: int):
        logits = outputs.logits
        weight = class_weights.to(logits.device)  # type: ignore
        return F.cross_entropy(logits, labels, weight=weight)

    # cria modelo novo para cada matéria (sem compartilhar pesos de saída)
    model = BertForSequenceClassification.from_pretrained(
        model_path,
        num_labels=len(id2label),
        id2label=id2label,
        label2id=label2id,
    )
    model.resize_token_embeddings(len(tokenizer))

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
        compute_loss_func=weighted_ce_loss,
        callbacks=[early_stopping_callback],
    )

    print(f"\n=== Treinamento preliminar: {subject} ===")
    trainer.train()

    best_epoch = get_best_epoch_from_trainer(trainer)
    print(f"Best epoch for {model_name}: {best_epoch}")

    # ======== final training (refit) ===========
    print(f"\n=== Treinamento final modelo (refit): {model_name} ===")

    masked_full_train = pd.concat([masked_train, masked_val], ignore_index=True)
    full_train_dataset = QuestoesDataset(masked_full_train)

    # recalcula peso das classes específico para a matéria
    class_weights = compute_class_weight(
        class_weight="balanced",
        classes=np.unique(masked_full_train["label"]),
        y=masked_full_train["label"],
    )
    class_weights = torch.tensor(class_weights, dtype=torch.float)

    # cria modelo novo para o treino final
    model = BertForSequenceClassification.from_pretrained(
        model_path,
        num_labels=len(id2label),
        id2label=id2label,
        label2id=label2id,
    )
    model.resize_token_embeddings(len(tokenizer))

    final_training_args = TrainingArguments(
        output_dir="./modelos-treinamento-final",  # Pasta para salvar o modelo
        num_train_epochs=best_epoch,  # Número de épocas baseado no melhor da prévia # type: ignore
        per_device_train_batch_size=12,  # Tamanho do batch de treino.
        per_device_eval_batch_size=24,  # Tamanho do batch de avaliação
        learning_rate=3e-5,
        weight_decay=0.01,
        warmup_ratio=0.1,
        save_strategy="no",  # Não precisa salvar checkpoints intermediários
        eval_strategy="no",  # Não avalia (não tem dataset de validação)
        logging_strategy="epoch",
    )

    final_trainer = Trainer(
        model=model,
        args=final_training_args,
        train_dataset=full_train_dataset,
        compute_metrics=compute_metrics,
        compute_loss_func=weighted_ce_loss,
    )

    final_trainer.train()

    # ======== inferencia ===========

    # Teste Gold (filtrado pela matéria atual)
    masked_test_gold = df_test[df_test["materia"] == subject].copy()
    masked_test_gold["label"] = masked_test_gold["topico"].map(label2id)
    ids_gold = masked_test_gold["id"]
    true_labels = masked_test_gold["topico"].tolist()

    test_dataset = QuestoesDataset(masked_test_gold)

    predictions = final_trainer.predict(test_dataset)
    predictions = np.argmax(predictions.predictions, axis=-1)
    predictions = [id2label[pred] for pred in predictions]

    df_preds_gold = pd.DataFrame()
    df_preds_gold["id"] = ids_gold
    df_preds_gold["subject_true"] = subject
    df_preds_gold["y_true"] = true_labels
    df_preds_gold["y_pred_gold"] = predictions

    # Teste Real (filtrado pela predição do BERT na matéria atual)
    masked_test_real = df_test[df_test["bert_pred_subject"] == subject].copy()
    masked_test_real["label"] = masked_test_real["topico"].map(label2id)
    masked_test_real["label"] = masked_test_real["label"].fillna(0).astype(int)
    ids_real = masked_test_real["id"]

    test_dataset = QuestoesDataset(masked_test_real)

    predictions = final_trainer.predict(test_dataset)
    predictions = np.argmax(predictions.predictions, axis=-1)
    predictions = [id2label[pred] for pred in predictions]

    df_preds_real = pd.DataFrame()
    df_preds_real["id"] = ids_real
    df_preds_real["subject_bert"] = subject
    df_preds_real["y_pred_real"] = predictions

    # Merge DFs
    df_preds_merged = pd.merge(
        df_preds_gold,
        df_preds_real,
        on=["id"],
        how="outer",
    )
    df_preds_merged["model"] = model_name

    return df_preds_merged


preds_dfs = []
for model_name, model_path in MODELS.items():
    print(f"\n=== Processando modelo: {model_name} ===")

    for subject in subjects:
        preds = train_preds(subject)
        preds_dfs.append(preds)

# ======== saving ===========
df_final_results = pd.concat(preds_dfs, ignore_index=True)
df_consolidado = df_final_results.groupby(["id", "model"], as_index=False).first()
df_consolidado.to_csv(
    f"{RESULTS_DIR}/transformers-predictions.csv",
    index=False,
)

print("Processamento concluído e arquivos salvos!")

/home/murilob/codes/tcc/artigo-murilo/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

=== Processando modelo: distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`

=== Treinamento preliminar: geografia ===

Best epoch for distilbert: 7.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: historia ===

Best epoch for distilbert: 4.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: portugues ===

Best epoch for distilbert: 6.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: fisica ===

Best epoch for distilbert: 7.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: biologia ===

Best epoch for distilbert: 6.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: quimica ===

Best epoch for distilbert: 5.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: literatura ===

Best epoch for distilbert: 5.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: matematica ===

Best epoch for distilbert: 5.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: artes ===

Best epoch for distilbert: 9.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: filosofia ===

Best epoch for distilbert: 4.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: sociologia ===

Best epoch for distilbert: 10.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: idiomas ===

Best epoch for distilbert: 1.0

=== Treinamento final modelo (refit): distilbert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at adalbertojunior/distilbert-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Processando modelo: bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: geografia ===

Best epoch for bert: 6.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: historia ===

Best epoch for bert: 6.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: portugues ===

Best epoch for bert: 8.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: fisica ===

Best epoch for bert: 5.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: biologia ===

Best epoch for bert: 8.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: quimica ===

Best epoch for bert: 6.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: literatura ===

Best epoch for bert: 5.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: matematica ===

Best epoch for bert: 9.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: artes ===

Best epoch for bert: 3.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: filosofia ===

Best epoch for bert: 5.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: sociologia ===

Best epoch for bert: 3.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== Treinamento preliminar: idiomas ===

Best epoch for bert: 1.0

=== Treinamento final modelo (refit): bert ===

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at neuralmind/bert-base-portuguese-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Processamento concluído e arquivos salvos!